apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cd-argocd-objects
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-argo-cd
    helm.sh/chart: {{ .Chart.Version | quote }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: ArgoCD
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/component: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: tools
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: 'https://argoproj.github.io/argo-helm'
    targetRevision: {{ .Values.argocdapps.targetRevision | quote }}
    chart: argocd-apps
    helm:
      values: |
        projects: 
        - name: tools-cd
          namespace: tools
          additionalLabels: {}
          additionalAnnotations: {}
          description: CD Tools
          sourceRepos:
          - git@github.com:know-ops/infra-hq.git
          - https://argoproj.github.io/argo-helm
          destinations:
          - namespace: tools
            server: https://kubernetes.default.svc
          clusterResourceWhitelist:
          - group: '*'
            kind: '*'
          orphanedResources: {}
          roles: []

        - name: cd-argocd
          namespace: tools
          additionalLabels: {}
          additionalAnnotations: {}
          description: ArgoCD specific Objects
          sourceRepos:
          - https://argoproj.github.io/argo-helm
          destinations:
          - namespace: tools
            server: https://kubernetes.default.svc
          namespaceResourceWhitelist:
          - group: 'argoproj.io'
            kind: '*'
          orphanedResources: {}
          roles: []

        - name: tools-ci
          namespace: tools
          additionalLabels: {}
          additionalAnnotations: {}
          description: CI Tools
          sourceRepos:
          - git@github.com:know-ops/infra-hq.git
          - https://codecentric.github.io/helm-charts
          destinations:
          - namespace: tools
            server: https://kubernetes.default.svc
          clusterResourceWhitelist:
          - group: '*'
            kind: '*'
          orphanedResources: {}
          roles: []

        - name: tools-infra
          namespace: tools
          additionalLabels: {}
          additionalAnnotations: {}
          description: Infrastructure Tools
          sourceRepos:
          - git@github.com:know-ops/infra-hq.git
          - https://charts.jetstack.io
          destinations:
          - namespace: tools
            server: https://kubernetes.default.svc
          - namespace: cert-manager
            server: https://kubernetes.default.svc
          clusterResourceWhitelist:
          - group: '*'
            kind: '*'
          orphanedResources: {}
          roles: []

        applications:
        - name: cd-apps
          project: tools-cd
          source:
            path: cd/apps
            repoURL: git@github.com:know-ops/infra-hq.git
            targetRevision: feature/initial_version
          destination:
            namespace: tools
            server: https://kubernetes.default.svc
          syncPolicy:
            automated:
              selfHeal: true

        - name: infra-apps
          project: tools-infra
          source:
            path: infra/apps
            repoURL: git@github.com:know-ops/infra-hq.git
            targetRevision: feature/initial_version
          destination:
            namespace: tools
            server: https://kubernetes.default.svc
          syncPolicy:
            automated:
              selfHeal: true

  project: cd-argocd
  syncPolicy:
    automated: 
      selfHeal: true
  ignoreDifferences:
  - group: argoproj.io/v1alpha1
    kind: Application
    name: cd-apps
    namespace: tools
    jsonPointers:
    - /